name: pakyouare
favicon: null
layout_spectrum: 0.6797314549330622
typography_spectrum: 0.5332419390324503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.3895744245965034
  lightness: 0.13245873572304845
  saturation: 0.11378262750804424
  rhythmicContrast: 0.30108763347379863
purpose: []
